/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.aidvps.druid.differ.internal.generator;

import static org.junit.jupiter.api.Assertions.*;

import com.aidvps.druid.differ.DatabaseDialect;
import com.aidvps.druid.differ.internal.comparator.ChangeDetector;
import com.aidvps.druid.differ.internal.model.*;
import com.aidvps.druid.differ.internal.model.constraint.PrimaryKey;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Tests for PostgreSQLMigrationGenerator.
 *
 * <p>These tests verify PostgreSQL-specific syntax including:
 *
 * <ul>
 *   <li>ALTER TABLE ... ALTER COLUMN TYPE (not MODIFY COLUMN)
 *   <li>GENERATED BY DEFAULT AS IDENTITY for auto-increment
 *   <li>PostgreSQL-specific data types (UUID, JSONB, TEXT)
 *   <li>USING clauses for type conversions
 *   <li>Constraint name requirements
 * </ul>
 */
public class PostgreSQLMigrationGeneratorTest {

    private PostgreSQLMigrationGenerator generator;
    private ChangeDetector detector;

    @BeforeEach
    public void setup() {
        generator = new PostgreSQLMigrationGenerator(false);
        detector = new ChangeDetector();
    }

    /** Helper method to create a SchemaDiff for table modifications. */
    private SchemaDiff createTableDiff(String tableName, Table sourceTable, Table targetTable) {
        Schema sourceSchema =
                Schema.builder(DatabaseDialect.POSTGRESQL).addTable(sourceTable).build();
        Schema targetSchema =
                Schema.builder(DatabaseDialect.POSTGRESQL).addTable(targetTable).build();
        return detector.compare(sourceSchema, targetSchema);
    }

    /** Helper method to create a SchemaDiff for added tables. */
    private SchemaDiff createAddedTableDiff(Table table) {
        Schema sourceSchema = Schema.builder(DatabaseDialect.POSTGRESQL).build();
        Schema targetSchema = Schema.builder(DatabaseDialect.POSTGRESQL).addTable(table).build();
        return detector.compare(sourceSchema, targetSchema);
    }

    /** Test ALTER COLUMN TYPE generation. */
    @Test
    public void testAlterColumnTypeGeneration() {
        // Create source and target tables with different column types
        Table sourceTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("name", "VARCHAR").length(100).build())
                        .build();

        Table targetTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("name", "TEXT").build())
                        .build();

        SchemaDiff diff = createTableDiff("users", sourceTable, targetTable);

        List<String> statements = generator.generate(diff);

        // Verify ALTER COLUMN TYPE syntax
        assertTrue(
                statements.stream().anyMatch(s -> s.contains("ALTER COLUMN")),
                "Should contain ALTER COLUMN syntax");

        // PostgreSQL uses ALTER COLUMN TYPE, not MODIFY COLUMN
        assertFalse(
                statements.stream().anyMatch(s -> s.contains("MODIFY COLUMN")),
                "Should not contain MODIFY COLUMN syntax");
        assertTrue(
                statements.stream().anyMatch(s -> s.contains("ALTER COLUMN name TYPE TEXT")),
                "Should contain ALTER COLUMN name TYPE TEXT");
    }

    /** Test IDENTITY generation for auto-increment columns. */
    @Test
    public void testIdentityGeneration() {
        Table targetTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").autoIncrement(true).build())
                        .addColumn(Column.builder("name", "VARCHAR").length(100).build())
                        .build();

        List<String> statements = generator.generate(createAddedTableDiff(targetTable));

        // Verify IDENTITY syntax
        assertTrue(
                statements.stream().anyMatch(s -> s.contains("GENERATED BY DEFAULT AS IDENTITY")),
                "Should use GENERATED BY DEFAULT AS IDENTITY for PostgreSQL");

        assertFalse(
                statements.stream().anyMatch(s -> s.contains("AUTO_INCREMENT")),
                "Should not use MySQL's AUTO_INCREMENT syntax");
    }

    /** Test PostgreSQL-specific data types. */
    @Test
    public void testPostgreSQLSpecificTypes() {
        Table targetTable =
                Table.builder("data")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("uuid_col", "UUID").build())
                        .addColumn(Column.builder("jsonb_col", "JSONB").build())
                        .addColumn(Column.builder("text_col", "TEXT").build())
                        .build();

        List<String> statements = generator.generate(createAddedTableDiff(targetTable));

        // Verify PostgreSQL-specific types are preserved
        assertTrue(
                statements.stream().anyMatch(s -> s.contains("UUID")), "Should preserve UUID type");
        assertTrue(
                statements.stream().anyMatch(s -> s.contains("JSONB")),
                "Should preserve JSONB type");
        assertTrue(
                statements.stream().anyMatch(s -> s.contains("TEXT")), "Should preserve TEXT type");
    }

    /** Test USING clause generation for type conversions. */
    @Test
    public void testUsingClauseGeneration() {
        Table sourceTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("email", "VARCHAR").length(255).build())
                        .build();

        Table targetTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("email", "TEXT").build())
                        .build();

        List<String> statements =
                generator.generate(createTableDiff("users", sourceTable, targetTable));

        // Verify USING clause for VARCHAR to TEXT conversion
        assertTrue(
                statements.stream().anyMatch(s -> s.contains("USING")),
                "Should include USING clause for type conversion");

        assertTrue(
                statements.stream().anyMatch(s -> s.contains("::text")),
                "Should include cast expression in USING clause");
    }

    /** Test constraint name requirements for DROP CONSTRAINT. */
    @Test
    public void testConstraintNameRequirements() {
        // Create table with primary key constraint
        Table sourceTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("name", "VARCHAR").length(100).build())
                        .addConstraint("pk_users", new PrimaryKey("pk_users", Arrays.asList("id")))
                        .build();

        Table targetTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("name", "VARCHAR").length(100).build())
                        .build();

        List<String> statements =
                generator.generate(createTableDiff("users", sourceTable, targetTable));

        // PostgreSQL requires constraint names for DROP CONSTRAINT
        assertTrue(
                statements.stream().anyMatch(s -> s.contains("DROP CONSTRAINT")),
                "Should use DROP CONSTRAINT (not DROP PRIMARY KEY)");
        assertTrue(
                statements.stream().anyMatch(s -> s.contains("pk_users")),
                "Should specify constraint name");
    }

    /** Test that ALTER TABLE operations are separate statements. */
    @Test
    public void testSeparateAlterTableStatements() {
        Table sourceTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("name", "VARCHAR").length(100).build())
                        .build();

        Table targetTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("name", "VARCHAR").length(200).build())
                        .addColumn(Column.builder("email", "VARCHAR").length(255).build())
                        .build();

        List<String> statements =
                generator.generate(createTableDiff("users", sourceTable, targetTable));

        // Each ALTER TABLE operation should be a separate statement
        long alterTableCount = statements.stream().filter(s -> s.startsWith("ALTER TABLE")).count();

        assertTrue(alterTableCount > 0, "Should have ALTER TABLE statements");
    }

    /** Test adding columns with default values. */
    @Test
    public void testAddColumnWithDefault() {
        Table targetTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("status", "INT").defaultValue("1").build())
                        .build();

        List<String> statements = generator.generate(createAddedTableDiff(targetTable));

        assertTrue(
                statements.stream().anyMatch(s -> s.contains("DEFAULT 1")),
                "Should include DEFAULT clause");
    }

    /** Test adding columns with NOT NULL constraint. */
    @Test
    public void testAddColumnWithNotNull() {
        Table targetTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(
                                Column.builder("name", "VARCHAR")
                                        .length(100)
                                        .nullable(false)
                                        .build())
                        .build();

        List<String> statements = generator.generate(createAddedTableDiff(targetTable));

        assertTrue(
                statements.stream().anyMatch(s -> s.contains("NOT NULL")),
                "Should include NOT NULL constraint");
    }

    /** Test type conversion from INTEGER to VARCHAR. */
    @Test
    public void testIntegerToVarcharConversion() {
        Table sourceTable =
                Table.builder("data")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("code", "INTEGER").build())
                        .build();

        Table targetTable =
                Table.builder("data")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("code", "VARCHAR").length(50).build())
                        .build();

        List<String> statements =
                generator.generate(createTableDiff("data", sourceTable, targetTable));

        // Should have ALTER COLUMN TYPE with USING clause
        assertTrue(
                statements.stream().anyMatch(s -> s.contains("ALTER COLUMN code TYPE VARCHAR(50)")),
                "Should alter column type");
    }

    /** Test generating CREATE TABLE with proper syntax. */
    @Test
    public void testCreateTableGeneration() {
        Table table =
                Table.builder("products")
                        .addColumn(Column.builder("id", "INT").autoIncrement(true).build())
                        .addColumn(
                                Column.builder("name", "VARCHAR")
                                        .length(200)
                                        .nullable(false)
                                        .build())
                        .addColumn(
                                Column.builder("price", "DECIMAL")
                                        .precision(10, 2)
                                        .defaultValue("0.00")
                                        .build())
                        .addConstraint(
                                "pk_products", new PrimaryKey("pk_products", Arrays.asList("id")))
                        .build();

        List<String> statements = generator.generate(createAddedTableDiff(table));

        String createTableStatement =
                statements.stream().filter(s -> s.contains("CREATE TABLE")).findFirst().orElse("");

        // Verify PostgreSQL syntax
        assertTrue(createTableStatement.contains("CREATE TABLE"), "Should contain CREATE TABLE");
        assertTrue(
                createTableStatement.contains("GENERATED BY DEFAULT AS IDENTITY"),
                "Should use IDENTITY for auto-increment");
        assertFalse(
                createTableStatement.contains("AUTO_INCREMENT"),
                "Should not use MySQL AUTO_INCREMENT syntax");
    }

    /** Test empty diff produces no statements. */
    @Test
    public void testEmptyDiffProducesNoStatements() {
        Schema emptySchema = Schema.builder(DatabaseDialect.POSTGRESQL).build();
        SchemaDiff emptyDiff = detector.compare(emptySchema, emptySchema);
        List<String> statements = generator.generate(emptyDiff);

        assertTrue(statements.isEmpty(), "Empty diff should produce no statements");
    }

    /** Test adding index statements. */
    @Test
    public void testAddIndex() {
        Table sourceTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("email", "VARCHAR").length(255).build())
                        .build();

        Table targetTable =
                Table.builder("users")
                        .addColumn(Column.builder("id", "INT").build())
                        .addColumn(Column.builder("email", "VARCHAR").length(255).build())
                        .addIndex(
                                new Index.Builder()
                                        .name("idx_users_email")
                                        .addColumn("email")
                                        .unique(true)
                                        .build())
                        .build();

        List<String> statements =
                generator.generate(createTableDiff("users", sourceTable, targetTable));

        assertTrue(
                statements.stream().anyMatch(s -> s.contains("CREATE UNIQUE INDEX")),
                "Should create unique index");
        assertTrue(
                statements.stream().anyMatch(s -> s.contains("idx_users_email")),
                "Should include index name");
    }
}
